### ISSUE TITLE
The bubbles dont colide with the edges of the screen  

### ISSUE THREAD

**Issue by ItsBenDov** [ShaharMS/spacebubble.io#2]
### **Where:**
The bubbles
![image](https://user-images.githubusercontent.com/98546220/178148560-d37a994f-ad2d-49c4-ab46-115056f7040d.png)

### **Issue:**
Make the bubbles collide with the edges of the screen

**Comment by ShaharMS** [comment]
implemented, might improve later on but its pretty good right now
