### ISSUE TITLE
Make the navigation bar constant

### ISSUE THREAD

**Issue by ItsBenDov** [ShaharMS/spacebubble.io#3]
### Where?
The navigation bar

### Issue
The navigation bar does not have a bar behind him, and when you scroll down the page, it is behind the youtube video preview.
1. please make the navigation bar above the YouTube preview
2. add a purple bar `#480F62` behind the text in the navigation bar

**Comment by ShaharMS** [comment]
![image](https://user-images.githubusercontent.com/88977041/179027450-f8b4926b-84b8-4ec5-bd5f-91f7fcbcd4c4.png)
looks pretty good for now, closing this
